CREATE TABLE "AWP_ADAPTER"."AWP_USER_ADAPTER"
(
	"ID" NUMBER(38, 0) NOT NULL ENABLE,
	"AUTH_USER_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"JWT_USER_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"USER_NAME" VARCHAR2 (255 BYTE),
	"BUSINESS_UNIT_ID" VARCHAR2 (255 BYTE),
	"ACCESS_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"VERSION" NUMBER(38, 0),
	"SPI_VERSION" VARCHAR2 (255 BYTE),
	"CREATED_BY" VARCHAR2 (255 BYTE),
	"CREATED_DATE" DATE,
	"UPDATED_BY" VARCHAR2 (255 BYTE),
	"UPDATED_DATE" DATE,
	PRIMARY KEY ("ID"),
);

commit;


