CREATE TABLE "AWP_ADAPTER"."AUTH_ENTITY_ADAPTER"
(
	"ID" NUMBER(38, 0) NOT NULL ENABLE,
	"OBJECT_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"ACCESS_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"ENTITY_TYPE" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"USER_NAME" VARCHAR2 (255 BYTE),
	"VERSION" NUMBER(38, 0),
	"SPI_VERSION" VARCHAR2 (255 BYTE),
	"CREATED_BY" VARCHAR2 (255 BYTE),
	"CREATED_DATE" DATE,
	"UPDATED_BY" VARCHAR2 (255 BYTE),
	"UPDATED_DATE" DATE
	"USER_ID" NUMBER(38, 0),
	PRIMARY KEY ("ID"),
	FOREIGN KEY ("USER_ID") REFERENCES ("ID")
);

commit;