CREATE TABLE "AWP_ADMIN"."AWP_USER_ADAPTER"
(
	"ID" INT PRIMARY KEY,
	"AUTH_USER_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"JWT_USER_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"USER_NAME" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"OBJECT_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"ACCESS_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"ENTITY_TYPE" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"BUSINESS_UNIT_ID" VARCHAR2 (255 BYTE) NOT NULL ENABLE,
	"VERSION" NUMBER(38, 0),
	"SPI_VERSION" VARCHAR2 (255 BYTE),
	"CREATED_BY" VARCHAR2 (255 BYTE),
	"CREATED_DATE" DATE,
	"UPDATED_BY" VARCHAR2 (255 BYTE),
	"UPDATED_DATE" DATE
);

commit;


